services:
  backend-service:
    build: 
      context: ./messaging.app
      dockerfile: Dockerfile.prod
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://abduls-pi:BloodhoundOctane123@chat-mongodb:27017/chatappauthSource=admin
    networks:
      - chatnet

  frontend-service:
    build: 
      context: ./messaging.app-frontend
      dockerfile: Dockerfile.prod
    container_name: chat-frontend
    ports:
      - "8080:80"
    networks:
      - chatnet
    depends_on:
      - backend-service

  mongodb:
    image: mongo:6.0
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: abduls-pi
      MONGO_INITDB_ROOT_PASSWORD: BloodhoundOctane123
    networks:
      - chatnet

volumes:
  mongo-data:

networks:
  chatnet: