FROM node:20 AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build
RUN ls -la /app/dist && cat /app/dist/index.html

FROM nginx:stable
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf